title: Kamran Ahmed
description: "Lead engineer at tajawal — tech guy with an entrepreneurial spirit and knack for getting things done"
url: "http://kamranahmed.info"
author: "Kamran Ahmed"
keywords: "kamran,kamranahmedse,kamran ahmed,code,javascript,php,databases,entrepreneurship,startups,react,angular,javascript"
github: kamranahmedse
medium: kamranahmedse
twitter: kamranahmedse
email: kamranahmedse@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: ["résumé.pdf"]

permalink: pretty
timezone: Asia/Abu_Dhabi

gems: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

featured:
  - id: 1
    title: Journey to HTTP/2
    date: 2016-08-13 12:30:00
    type: light
    url: /blog/2016/08/13/http-in-depth/
  - id: 2
    title: Web Cache in Depth
    date: 2017-03-14 11:50:00
    type: light
    url: /blog/2017/03/14/quick-guide-to-http-caching/

about:
  - name: Github
    username: kamranahmedse
    url: https://github.com/kamranahmedse
    class: github
  - name: Medium
    username: kamranahmedse
    url: https://medium.com/@kamranahmedse
    class: medium
  - name: Twitter
    username: kamranahmedse
    url: https://twitter.com/kamranahmedse
    class: twitter
  - name: Email
    username: kamranahmed.se@gmail.com
    class: email
    url: mailto:kamranahmed.se@gmail.com
